# Generated by Django 5.2.1 on 2025-06-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
