# Generated by Django 5.2.1 on 2025-06-02 01:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_heading',
            field=models.CharField(default=123, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
