# Generated by Django 5.2.1 on 2025-06-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_about_about_heading_about_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
